name: "PR"
on:
  issue_comment:
    types: [ created ]
jobs:
  write-comment:
    name: Write comment
    runs-on: ubuntu-latest
    if: >
      github.event.issue.pull_request &&
      (
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'OWNER'
      ) &&
      contains(github.event.comment.body, 'run kubernetes')
    outputs:
      comment_id: ${{ steps.create_comment.outputs.result }}
      head_sha: ${{ steps.get_pr_sha.outputs.pr_sha }}
    steps:
      - name: Get PR SHA
        id: get_pr_sha
        uses: actions/github-script@v8
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('pr_sha', pr.data.head.sha);
            return pr.data.head.sha;
      - name: Comment PR with Link
        id: create_comment
        uses: actions/github-script@v8
        with:
          script: |
            const runUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            const { data: comment } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🚧 Kubernetes workflow run started and I'll update this comment with results! [View the run here](${runUrl})`
            });
            return comment.id;
  kubernetes-build-jvm-latest:
    name: Kubernetes JVM
    runs-on: ubuntu-latest
    needs: write-comment
    strategy:
      matrix:
        include:
          - quarkus-version: "999-SNAPSHOT"
            java: 17
            extra-maven-args: ''
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ needs.write-comment.outputs.head_sha }}
      - name: Build
        run: |
          git log
  update-comment:
    name: Update comment
    runs-on: ubuntu-latest
    needs: [ write-comment, kubernetes-build-jvm-latest, kubernetes-build-native-latest ]
    if: always()
    steps:
      - name: Update PR comment with status
        uses: actions/github-script@v8
        with:
          script: |
            const runUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            let body;
            const jvmJobResult = '${{ needs.kubernetes-build-jvm-latest.result }}';
            const nativeJobResult = '${{ needs.kubernetes-build-native-latest.result }}';
            
            if (jvmJobResult === 'success' && nativeJobResult === 'success') {
              body = `✅ Kubernetes workflow finished successfully! [View the details here](${runUrl})`;
            } else {
              body = `Kubernetes workflow failed. ❌ \n\n` +
                      `• **JVM Build**: ${jvmJobResult}\n` +
                      `• **Native Build**: ${nativeJobResult}\n\n` +
                      `[View the details here](${runUrl})`;
            }
            
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ needs.write-comment.outputs.comment_id }},
              body: body
            });
